server:
  port: ${PORT:69}
  context-path: /upload

logging:
  path: "/logs/${spring.application.name}"
  level:
    com.sdca: DEBUG
spring:
  http:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 100Mb
  redis:
    database: 0
    host: 10.110.1.254
    password:
    port: 6379
    pool:
      max-active: 100
      max-idle: 100
      max-wait: -1
      min-idle: 0
    timeout: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  aop:
    proxy-target-class: true

file:
  local:
    path: D:/local/file